---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart traefik
  systemd:
    name: traefik
    state: restarted

- name: restart cloudflared
  systemd:
    name: cloudflared
    state: restarted
